project_name: creep
builds:
- main: ./cmd/creep/main.go
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  ldflags:
    - -s -w -X github.com/Splode/creep/internal/flags.Version={{ .Version }}
archives:
- replacements:
    darwin: macOS
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
